### ISSUE TITLE
Issue in Matomo

### ISSUE THREAD

**Issue by basavrajdevpuje** [kalfeher/blog_code#1]
Hello. Thank you for the solution. After trying your solution, I am getting the 403 Forbidden error. The log is ."Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive". Could you please help me to solve the problem?

**Comment by kalfeher** [comment]
Hi basavrajdevpuje, that isnt much to go on.
which container version are you using for matomo?
That directory is found under the volume mount. Have you confirmed it's claimed and mounted correctly?

**Comment by basavrajdevpuje** [comment]
Thank you very much for your quick response.

The MATOMO version according to the Github directory is 4.10.1.

The volume is mounted and claimed. ()
![image](https://user-images.githubusercontent.com/68498809/180388554-8ebba506-8ef8-4d3f-a976-0dc907cd7834.png)

I am using the NFS solution for PV (Refer the following screenshot)

![image](https://user-images.githubusercontent.com/68498809/180389409-68899db8-1a13-4170-99a7-b4d964fa87d1.png)

**Comment by basavrajdevpuje** [comment]
> Thank you very much for your quick response.
> 
> The MATOMO version according to the Github directory is 4.10.1.
> 
> The volume is mounted and claimed. () ![image](https://user-images.githubusercontent.com/68498809/180388554-8ebba506-8ef8-4d3f-a976-0dc907cd7834.png)
> 
> I am using the NFS solution for PV (Refer to the following screenshot)
> 
> ![image](https://user-images.githubusercontent.com/68498809/180389409-68899db8-1a13-4170-99a7-b4d964fa87d1.png)

I tried this locally `wget https://builds.matomo.org/matomo.zip && unzip matomo.zip` and some files which are listed here (Refer to the screenshot below) are missing in the mounted volume. 

![image](https://user-images.githubusercontent.com/68498809/180393951-b3151480-5f18-4620-8bc3-0f7298424314.png)

**Comment by basavrajdevpuje** [comment]
I got it now. I think it is all about the TAG used for the image. Previously I was using the TAG `matomo:latest` and hence it was not working. I wrote the tag as `matomo:4.10.1-apache` and it worked.

**Comment by kalfeher** [comment]
You may wish to report the issue to the matomo project if their latest image did not behave as expected.

**Comment by basavrajdevpuje** [comment]
@kalfeher Yes sure I will raise the issue on the Matomo Github repo. Thanks a ton for your solution. I really appreciate your efforts and your quick responses. 😊🙌

**Comment by basavrajdevpuje** [comment]
Hello,

I want to ask one more doubt.
I have deployed the Matomo App along with the Galera-MariaDB cluster on Kubernetes.

On the local system, the cron job for the Matomo app can be set. Please refer to the link: https://matomo.org/faq/on-premise/how-to-set-up-auto-archiving-of-your-reports/

I want to accomplish the same thing with Kubernetes. However, I'm confused about "How to set a cron job for the running pod?"

Is it possible to set cronjobs for the running pods? Or could you please suggest an alternative solution?

Thanks in advance.

**Comment by kalfeher** [comment]
I recommend starting with the official documentation for kubernetes.
https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/
