### ISSUE TITLE
opensearch, discovery.zen.minimum_master_nodes 

### ISSUE THREAD

**Issue by User-Piotr** [kalfeher/blog_code#2]
Hi, 

According to the information below, this option is no longer recognized and leads to an error.
https://github.com/opensearch-project/helm-charts/issues/141

https://github.com/kalfeher/blog_code/blob/fefb4778c647d459ace3dd0ba6c3844c839fa142/parsedmarc-k8s-opensearch/opensearch/os-sts.yaml#L43

**Comment by kalfeher** [comment]
Thanks for raising. will update to remove

**Comment by kalfeher** [comment]
https://github.com/kalfeher/blog_code/commit/2379402e2dfa864042e5d53cd5e4e3d841af541f
